"""Initial migration

Revision ID: 5ea61b219637
Revises: 
Create Date: 2025-06-14 10:11:33.176728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea61b219637'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('close', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symbol_timeframe_datetime', 'price_data', ['symbol', 'timeframe', 'datetime'], unique=False)
    op.create_index(op.f('ix_price_data_datetime'), 'price_data', ['datetime'], unique=False)
    op.create_index(op.f('ix_price_data_id'), 'price_data', ['id'], unique=False)
    op.create_index(op.f('ix_price_data_symbol'), 'price_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_price_data_timeframe'), 'price_data', ['timeframe'], unique=False)
    op.create_table('system_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_trading_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('active_strategies', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_status_id'), 'system_status', ['id'], unique=False)
    op.create_table('technical_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('dow_trend', sa.String(length=20), nullable=True),
    sa.Column('elliott_wave_count', sa.String(length=10), nullable=True),
    sa.Column('swing_points', sa.Text(), nullable=True),
    sa.Column('signals', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_analysis_datetime'), 'technical_analysis', ['datetime'], unique=False)
    op.create_index(op.f('ix_technical_analysis_id'), 'technical_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_technical_analysis_symbol'), 'technical_analysis', ['symbol'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=10, scale=5), nullable=True),
    sa.Column('position_size', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('profit_loss', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_technical_analysis_symbol'), table_name='technical_analysis')
    op.drop_index(op.f('ix_technical_analysis_id'), table_name='technical_analysis')
    op.drop_index(op.f('ix_technical_analysis_datetime'), table_name='technical_analysis')
    op.drop_table('technical_analysis')
    op.drop_index(op.f('ix_system_status_id'), table_name='system_status')
    op.drop_table('system_status')
    op.drop_index(op.f('ix_price_data_timeframe'), table_name='price_data')
    op.drop_index(op.f('ix_price_data_symbol'), table_name='price_data')
    op.drop_index(op.f('ix_price_data_id'), table_name='price_data')
    op.drop_index(op.f('ix_price_data_datetime'), table_name='price_data')
    op.drop_index('idx_symbol_timeframe_datetime', table_name='price_data')
    op.drop_table('price_data')
    # ### end Alembic commands ###
